name: Creating artifact

on:
  push:
    branches:
      - add-github-workflow


jobs:

  build:
  
    strategy:
        matrix:
          include:
            - os: ubuntu-latest
              exe-path: ./Renegade/Renegade
              artifact-name: renegade-ubuntu
              build-arch: x86-64-bmi2
            - os: windows-latest
              exe-path: Renegade\Renegade.exe
              artifact-name: renegade-windows.exe
              build-arch: x86-64-bmi2
            - os: macos-latest
              exe-path: ./Renegade/Renegade
              artifact-name: renegade-macos
              build-arch: native

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd Renegade
          make build=${{ matrix.build-arch }}
      
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: ${{ matrix.exe-path }} bench | tail -n 1
        
      - if: runner.os == 'Windows'
        shell: powershell
        run: ${{ matrix.exe-path }} bench | Select-Object -Last 1
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.exe-path }}