name: Renegade

on:
  push:
    branches:
      - add-github-workflow

jobs:
  build:
    strategy:
        matrix:
          include:
            - name: Ubuntu
              os: ubuntu-latest
              exe-path: ./Renegade/Renegade
              artifact-name: renegade-ubuntu-bmi2
            - name: Windows
              os: windows-latest
              exe-path: Renegade\Renegade.exe
              artifact-name: renegade-windows-bmi2.exe

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Compiling
        run: |
          cd Renegade
          make build=x86-64-bmi2
      
      - name: Running bench (Linux)
        if: runner.os == 'Linux'
        run: ${{ matrix.exe-path }} bench | tail -n 1
          
      - name: Running bench (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: ${{ matrix.exe-path }} bench | Select-Object -Last 1
      
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.exe-path }}