name: Creating artifact

on:
  push:
    branches:
      - add-github-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd Renegade
          make build=x86-64-bmi2
      - uses: actions/upload-artifact@v4
        with:
          name: renegade-ubuntu
          path: ./Renegade/Renegade